version: '3.7'
services:
  db:
    container_name: db
    image: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: document_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    networks:
      - db
  php:
    container_name: php-fpm
    build: ./docker/php-fpm
    ports:
      - "9000:9001"
    volumes:
      - .:/var/www/app
      - ./logs/php:/var/www/app/var/log
    depends_on:
      - db
    networks:
      - db
      - php
  nginx:
    container_name: nginx
    build: ./docker/nginx
    ports:
      - "8082:80"
    depends_on:
      - php
    networks:
      - php
    volumes:
      - ./logs/nginx:/var/log/nginx
      - .:/var/www/app
  adminer:
    image: adminer
    depends_on:
      - db
    restart: always
    ports:
      - "8002:8080"
    networks:
      - db
networks:
  db:
  php:
